config/routes.rb
AgilefamilyAlpha::Application.routes.draw do
  devise_for :family_members, :path => "accounts"
  # match '/foo', :to => redirect('/foo.html')
  # root :to => "families#index"
  resources :families
  resources :tasks
  resources :family_members
end

app/models/family.rb
class Family < ActiveRecord::Base
  attr_accessible :meeting_day, :mission_statement, :name, :meeting_time

  has_many :family_members
  has_many :tasks, through: :family_members

  validates :name, presence: true
  validates :mission_statement, presence: true
  validates :meeting_day, presence: true

end

app/models/family_member.rb
class FamilyMember < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :age, :family_id, :name, :phone, :role, :accepted

  before_validation :clean_phone_number

  belongs_to :family
  has_many :tasks
  has_many :task_logs

  # validates :name, presence: true
  # validates :phone, uniqueness: true

  def clean_phone_number
    number = self.phone

    if number
      unless number[0..1] == "+1"
        number.gsub!(/[^0-9]/, '')
        self.phone = "+1#{number}"
      end
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :family_member_id, :complete

  belongs_to :task_log
  belongs_to :family_member
  has_many :task_weekdays, dependent: :destroy
  has_many :weekdays, through: :task_weekdays

  validates :description, presence: true

  def addTasks(ajaxResponse)
    #numbers correspond to days of the week starting with Monday, which equals 1
    ajaxResponse[0].each_pair{ |x, y|
      x == "1" && y == "true" ? weekdays << Weekday.find_by_weekday("1") : nil
      x == "2" && y == "true" ? weekdays << Weekday.find_by_weekday("2") : nil
      x == "3" && y == "true" ? weekdays << Weekday.find_by_weekday("3") : nil
      x == "4" && y == "true" ? weekdays << Weekday.find_by_weekday("4") : nil
      x == "5" && y == "true" ? weekdays << Weekday.find_by_weekday("5") : nil
      x == "6" && y == "true" ? weekdays << Weekday.find_by_weekday("6") : nil
      x == "7" && y == "true" ? weekdays << Weekday.find_by_weekday("7") : nil
    }
  end
end

app/models/task_log.rb
class TaskLog < ActiveRecord::Base
  attr_accessible :complete, :due_date, :family_member_id, :task_id

  belongs_to :family_member
  has_one :task

  validates :due_date, presence: true
end

app/models/task_weekday.rb
class TaskWeekday < ActiveRecord::Base
  attr_accessible :task_id, :weekday_id, :complete

  belongs_to :task
  belongs_to :weekday

end

app/models/weekday.rb
class Weekday < ActiveRecord::Base
  attr_accessible :weekday

  has_many :task_weekdays
  #validates_inclusion_of :weekday, :in => %w(monday, tuesday, wednesday, thursday, friday, saturday, sunday)
   # :message => "{{value}} is not a valid day"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    if current_family_member.family_id
      family_path(current_family_member.family_id)
    else
      new_family_path
    end
  end

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_filter :authenticate_family_member!

  def index
    @family = Family.find(current_family_member.family_id)
    redirect_to family_path(@family)
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.create(params[:family])
    current_family_member.update_attributes(family_id: @family.id, accepted: true)
    redirect_to family_path(@family)
  end

  def show
    @family = Family.find(current_family_member.family_id)
    @family_members = @family.family_members

    respond_to do |format|
      format.html
      format.json {
        render json: @family_members
      }
    end
  end
end

app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  def update
    # family_id = params[:family_member][:family_id]
    # current_family_member.update_attributes(family_id: family_id, accepted: false)
    # redirect_to "/families/#{family_id}"

    @family_member = FamilyMember.find(current_family_member.id)
    puts "*"*30
    p params[:accepted]

    if @family_member.family_id == nil
      family_id = params[:family_member][:family_id]
      current_family_member.update_attributes(family_id: family_id, accepted: false)
      redirect_to "/families/#{family_id}"
      return
    elsif params[:accepted] == "true"
      family_member = FamilyMember.find(params[:id])
      family_member.update_attributes(accepted: true, family_id: params[:family_id])
    elsif params[:accepted] == "false"
      family_member = FamilyMember.find(params[:id])
      family_member.update_attributes(accepted: false)
    end
    respond_to do |format|
      format.html
      format.json {render json: @family_member}
    end
  end

  def show
    @tasks = Task.where("family_member_id = ?", params[:id])

    tasks_info = []

    @tasks.each do |task|
      tasks_info << {task: task, days: task.task_weekdays.map do |day|
        day.as_json.merge({weekday: day.weekday.weekday})
      end}
    end

    respond_to do |format|
      format.json {render json: tasks_info}
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_family_member!

  def index
    family_member_id = current_family_member.family_id
    @family_members = FamilyMember.where("family_id = ?", family_member_id)
    respond_to do |format|
      format.html
      format.json {
        render json: {
          familyMembers: @family_members
        }
      }
    end
  end

  def create
    ajaxResponse = params[:_json]
    family_member_id = ajaxResponse[0][:userId]
    description = ajaxResponse[0][:description]
    @task = Task.create(family_member_id: family_member_id, description: description)
    @task.addTasks(ajaxResponse)
    respond_to do |format|
      format.json { render json: @task }
    end
  end

  def show

  end

  def update
    @task = Task.find_by_id(params[:id])
    taskWeekday = TaskWeekday.find_by_id(params[:data])
    taskWeekday.update_attributes(complete: true)
    puts "*"*30
    p taskWeekday
    respond_to do |format|
      format.json { render json: @task }
    end

  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/families/_show.html.erb
<% if current_family_member.accepted == true && @family.id == current_family_member.family_id %>
  <div class="col-md-6">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">My Family:</h3>
      </div>
      <div class="panel-body">
        <strong>Name:</strong> <%= @family.name %><br />
        <strong>Mission Statement:</strong> <%= @family.mission_statement %><br />
        <strong>Meeting Day:</strong> <%= @family.meeting_day %><br />
        <strong>Meeting Time:</strong> <%= @family.meeting_time.strftime("%I:%M %p") %><br />
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Invite Your Family</h3>
      </div>
      <div class="panel-body">
        <div class="text-center">Ask your family members to visit AgileFamily and enter your family id</div>
        <h2 class="text-center"><%= @family.id %> </h2>
        <input type="hidden" id="family_id" value="<%= @family.id %>" >
      </div>
    </div>
  </div>
  <div id="family-member-list" class="col-md-10">
    <h4>Family Members</h4>
    <table class="table">
      <thead>
        <th>Name</th>
        <th>Phone Number</th>
        <th>Email</th>
        <th>Age</th>
        <th>Authorization</th>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
<% else %>
  <h3> Your request to join this family has been received or you have been rejected by this family. Please check with your family members for more information. </h3>
<% end %>

app/views/families/index.html.erb
<h1>Family index page</h1>

app/views/families/new.html.erb
<h1 class="text-center"><small>Please select either option</small></h1>

<div class="col-md-6">
  <div class="panel-group" id="accordion">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          I already have a family profile<i class="fa fa-caret-square-o-down right"></i>
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse">
        <div class="panel-body">
          <%= form_for(current_family_member, class: "form-signin") do |f| %>
            <%= f.text_field :family_id, class: "form-control", "placeholder" => "Enter your family id" %><br />
            <%= f.submit "Add my family id", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-md-6">
  <div class="panel-group" id="accordion">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          I need to create a family profile<i class="fa fa-caret-square-o-down right"></i>
          </a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse">
        <div class="panel-body">
          <%= form_for(@family, class: "form-signin") do |f| %>
            <%= f.label :family_name %>:
            <%= f.text_field :name, class: "form-control", "placeholder" => "Family Name" %><br />

            <%= f.label :family_mission_statement %>:
            <%= f.text_field :mission_statement, class: "form-control", "placeholder" => "Family Mission Statement" %><br />

            <%= f.label :meeting_weekday %>:<br />
          <div class="btn-group">
            <label class="btn btn-default rating">
              <%= f.radio_button :meeting_day, 'Monday'%>
              <span>Mon</span>
            </label>
            <label class="btn btn-default rating">
            <%= f.radio_button :meeting_day, 'Tuesday'%>
              <span>Tue</span>
            </label>
            <label class="btn btn-default rating">
            <%= f.radio_button :meeting_day, "Wednesday"%>
              <span>Wed</span>
            </label>
            <label class="btn btn-default rating">
            <%= f.radio_button :meeting_day, "Thursday"%>
              <span>Thu</span>
            </label>
            <label class="btn btn-default rating">
            <%= f.radio_button :meeting_day, "Friday"%>
              <span>Fri</span>
            </label>
            <label class="btn btn-default rating">
            <%= f.radio_button :meeting_day, "Saturday"%>
              <span>Sat</span>
            </label>
            <label class="btn btn-default rating">
            <%= f.radio_button :meeting_day, "Sunday"%>
              <span>Sun</span>
            </label>
          </div><br /><br />

            <%= f.label :meeting_time %>: <input class="form-control" id="family_meeting_time" name="family[meeting_time]" type="time"><br />

            <%= f.submit "Create my family", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/families/show.html.erb
<%= render "show" %>

app/views/family_members/update.html.erb
update.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AgilefamilyAlpha</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/assets/favicon.ico" type="image/x-icon">
  <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans+SC' rel='stylesheet' type='text/css'>
  <script src='https://cdn.firebase.com/v0/firebase.js'></script>
  <script src='https://cdn.firebase.com/libs/angularfire/0.5.0/angularfire.min.js'></script>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">More</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/families">agilefamily.co</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/families">My Family</a></li>
        <li><a href="/tasks">Tasks</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"></a></li>
        <% if current_family_member.present? %>
          <li><%= link_to 'Sign Out', destroy_family_member_session_path, :method => :delete %></li>
        <% else %>
          <li>
            <%= link_to "Sign up", new_family_member_registration_path %>
          </li>
          <li>
            <%= link_to "Sign in", new_family_member_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>


<div class="container">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <%= yield %>
</div>
</body>
</html>

app/views/tasks/index.html.erb
<h1>Weekly tasks</h1>
<div ng-app="taskSchedule">
  <div ng-controller="NamesController">
    <div class="btn-group">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        {{username}} <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li ng-repeat="(key,val) in appData.familyMembers" ng-click="fetch(val['id'],val['name'])">{{val['name']}}</li>
      </ul>
      <!-- <select ng-change="fetch()" ng-model="selectedName" ng-options="val as val['name'] for (key,val) in appData.familyMembers"></select> -->
    </div><br /><br />
    <table class="table table-bordered">
      <tr>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Saturday</th>
        <th>Sunday</th>
      </tr>
      <tr>
        <td id="taskData" ng-repeat="(day,task_descriptions) in taskData">
          <div ng-repeat="task in task_descriptions" ng-click="completeTask(task.id, task.taskWeekdayId)" ng-class="{active: task.complete == true}"> {{task.description}}<hr></div>
        </td>
      </tr>
    </table>
    <div ng-repeat="task in fbTasks">
      <table>
        <tr>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Saturday</th>
        <th>Sunday</th>
      </tr>
      <span ng-if="task.task.1 == true"></span>
    </div>
    <div class="panel panel-success">
      <div class="panel-heading"><strong>Add a Task</strong></div>
      <div class="panel-body">
        <form name="addTasker" role="form">
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              {{taskUsername}} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li ng-repeat="(key,val) in appData.familyMembers" ng-click="getUser(val['id'],val['name'])">{{val['name']}}</li>
            </ul>
      <!-- <select ng-change="fetch()" ng-model="selectedName" ng-options="val as val['name'] for (key,val) in appData.familyMembers"></select> -->
          </div><br />
          <h4>Select Weekdays:</h4>
          <div class="btn-group">
            <label class="btn btn-default">
              <input type="checkbox" ng-model="newTask.1" ng-true-value="true" ng-false-value="false"> Monday
            </label>
            <label class="btn btn-default">
              <input type="checkbox" ng-model="newTask.2" ng-true-value="true" ng-false-value="false"> Tuesday
            </label>
            <label class="btn btn-default">
              <input type="checkbox" ng-model="newTask.3" ng-true-value="true" ng-false-value="false"> Wednesday
            </label>
            <label class="btn btn-default">
              <input type="checkbox" ng-model="newTask.4" ng-true-value="true" ng-false-value="false"> Thursday
            </label>
            <label class="btn btn-default">
              <input type="checkbox" ng-model="newTask.5" ng-true-value="true" ng-false-value="false"> Friday
            </label>
            <label class="btn btn-default">
              <input type="checkbox" ng-model="newTask.6" ng-true-value="true" ng-false-value="false"> Saturday
            </label>
            <label class="btn btn-default">
              <input type="checkbox" ng-model="newTask.7" ng-true-value="true" ng-false-value="false"> Sunday
            </label>
          </div><br />
          <h4>Input Task Description:</h4>
          <input type='text' ng-model="newTask.description" class="form-control"><br />
          <button ng-click="addNewTask()" class="btn btn-success">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>